In [23]:
import pandas as pd
print (pd.__version__)
import numpy as np
import matplotlib as plt
import os

2.2.3

In [ ]:
stock_names = ['aal', 'aapl', 'adbe', 't', 'tmus']
folder = 'stock_market_dataset'

def create_multi_indexed_df(stock_names, folder):       # self-explanatory function.
    all_stocks = pd.DataFrame()         # create empty df to store values.
    
    # go over all stocks
    for stock in stock_names:
        
        file_path = os.path.join(folder, (stock + '.us.csv'))
        df = pd.read_csv(file_path)
        df['Ticker'] = stock        # add this column to create multi-index later.
        
        all_stocks = pd.concat(     # add stock data to df
            [all_stocks, df], 
            ignore_index = True
        )

    all_stocks['Date'] = pd.to_datetime(all_stocks['Date'])     # convert dates to datetime
    all_stocks = all_stocks.set_index(['Ticker', 'Date'])       # create multi-index
    
    return all_stocks

df = create_multi_indexed_df(stock_names, folder)
print(df)

                     Open    High     Low   Close    Volume  OpenInt
Ticker Date
aal    2013-12-10  23.698  24.345  23.610  24.064  18043837        0
       2013-12-11  24.607  26.288  24.539  25.139  43224764        0
       2013-12-12  25.342  25.832  24.616  24.616  20749989        0
       2013-12-13  24.771  25.437  24.684  25.369  12588700        0
       2013-12-16  25.749  25.888  25.485  25.739  17136729        0
...                   ...     ...     ...     ...       ...      ...
tmus   2017-11-06  56.200  56.500  54.930  55.540  16981806        0
       2017-11-07  55.780  56.030  54.600  55.350   8785391        0
       2017-11-08  55.360  56.415  55.240  56.220   5977832        0
       2017-11-09  56.500  56.569  55.630  56.000   5204316        0
       2017-11-10  55.690  57.040  55.540  56.800   5758882        0

[28293 rows x 6 columns]

In [25]:
print(df.index.get_level_values('Date'))
print(df.loc['aal'])

DatetimeIndex(['2013-12-10', '2013-12-11', '2013-12-12', '2013-12-13',
               '2013-12-16', '2013-12-17', '2013-12-18', '2013-12-19',
               '2013-12-20', '2013-12-23',
               ...
               '2017-10-30', '2017-10-31', '2017-11-01', '2017-11-02',
               '2017-11-03', '2017-11-06', '2017-11-07', '2017-11-08',
               '2017-11-09', '2017-11-10'],
              dtype='datetime64[ns]', name='Date', length=28293, freq=None)
              Open    High     Low   Close    Volume  OpenInt
Date
2013-12-10  23.698  24.345  23.610  24.064  18043837        0
2013-12-11  24.607  26.288  24.539  25.139  43224764        0
2013-12-12  25.342  25.832  24.616  24.616  20749989        0
2013-12-13  24.771  25.437  24.684  25.369  12588700        0
2013-12-16  25.749  25.888  25.485  25.739  17136729        0
...            ...     ...     ...     ...       ...      ...
2017-11-06  47.356  47.995  47.177  47.406   4258497        0
2017-11-07  47.406  47.406  46.299  46.358   3763615        0
2017-11-08  46.319  46.877  45.740  46.269   3205573        0
2017-11-09  45.750  46.249  45.261  45.670   3567014        0
2017-11-10  45.640  46.120  45.560  45.820   2433022        0

[989 rows x 6 columns]

In [26]:
def fill_missing_dates(df):
    stocks = df.index.get_level_values('Ticker').unique()
    res = pd.DataFrame()
    for stock in stocks:
        df1 = df.loc[stock]
        # print(stock, df1)
        all_dates = pd.date_range(
            df1.index.get_level_values('Date').min(),
            df1.index.get_level_values('Date').max()
        )
        df1 = df1.reindex(all_dates)
        # print(df1)
        df1['Ticker'] = stock
        df1 = df1.reset_index(names = ['Date'])
        # print(df1)
        res = pd.concat([res, df1], ignore_index=True)
    
    res = res.set_index(['Ticker', 'Date'])
    res = res.interpolate()

    return res
        
dff = fill_missing_dates(df)
print(dff)
for i in stock_names:
    print(i, dff.loc[i])
# print(df)

                     Open       High     Low      Close        Volume  OpenInt
Ticker Date
aal    2013-12-10  23.698  24.345000  23.610  24.064000  1.804384e+07      0.0
       2013-12-11  24.607  26.288000  24.539  25.139000  4.322476e+07      0.0
       2013-12-12  25.342  25.832000  24.616  24.616000  2.074999e+07      0.0
       2013-12-13  24.771  25.437000  24.684  25.369000  1.258870e+07      0.0
       2013-12-14  25.097  25.587333  24.951  25.492333  1.410471e+07      0.0
...                   ...        ...     ...        ...           ...      ...
tmus   2017-11-06  56.200  56.500000  54.930  55.540000  1.698181e+07      0.0
       2017-11-07  55.780  56.030000  54.600  55.350000  8.785391e+06      0.0
       2017-11-08  55.360  56.415000  55.240  56.220000  5.977832e+06      0.0
       2017-11-09  56.500  56.569000  55.630  56.000000  5.204316e+06      0.0
       2017-11-10  55.690  57.040000  55.540  56.800000  5.758882e+06      0.0

[40990 rows x 6 columns]
aal               Open       High     Low      Close        Volume  OpenInt
Date
2013-12-10  23.698  24.345000  23.610  24.064000  1.804384e+07      0.0
2013-12-11  24.607  26.288000  24.539  25.139000  4.322476e+07      0.0
2013-12-12  25.342  25.832000  24.616  24.616000  2.074999e+07      0.0
2013-12-13  24.771  25.437000  24.684  25.369000  1.258870e+07      0.0
2013-12-14  25.097  25.587333  24.951  25.492333  1.410471e+07      0.0
...            ...        ...     ...        ...           ...      ...
2017-11-06  47.356  47.995000  47.177  47.406000  4.258497e+06      0.0
2017-11-07  47.406  47.406000  46.299  46.358000  3.763615e+06      0.0
2017-11-08  46.319  46.877000  45.740  46.269000  3.205573e+06      0.0
2017-11-09  45.750  46.249000  45.261  45.670000  3.567014e+06      0.0
2017-11-10  45.640  46.120000  45.560  45.820000  2.433022e+06      0.0

[1432 rows x 6 columns]
aapl                  Open        High         Low       Close        Volume  \
Date
1984-09-07    0.42388    0.429020    0.418740    0.423880  2.322003e+07
1984-09-08    0.42388    0.427733    0.417047    0.423033  2.148753e+07
1984-09-09    0.42388    0.426447    0.415353    0.422187  1.975503e+07
1984-09-10    0.42388    0.425160    0.413660    0.421340  1.802253e+07
1984-09-11    0.42516    0.436680    0.425160    0.429020  4.249820e+07
...               ...         ...         ...         ...           ...
2017-11-06  171.75000  174.360000  171.100000  173.630000  3.490124e+07
2017-11-07  173.29000  174.510000  173.290000  174.180000  2.442488e+07
2017-11-08  174.03000  175.610000  173.710000  175.610000  2.445117e+07
2017-11-09  174.48000  175.460000  172.520000  175.250000  2.953309e+07
2017-11-10  175.11000  175.380000  174.270000  174.670000  2.513049e+07

            OpenInt
Date
1984-09-07      0.0
1984-09-08      0.0
1984-09-09      0.0
1984-09-10      0.0
1984-09-11      0.0
...             ...
2017-11-06      0.0
2017-11-07      0.0
2017-11-08      0.0
2017-11-09      0.0
2017-11-10      0.0

[12118 rows x 6 columns]
adbe                   Open        High     Low   Close        Volume  OpenInt
Date
1986-08-14    0.210000    0.210000    0.21    0.21  8.320000e+06      0.0
1986-08-15    0.210000    0.210000    0.20    0.20  8.665600e+06      0.0
1986-08-16    0.206667    0.206667    0.20    0.20  7.662933e+06      0.0
1986-08-17    0.203333    0.203333    0.20    0.20  6.660267e+06      0.0
1986-08-18    0.200000    0.200000    0.20    0.20  5.657600e+06      0.0
...                ...         ...     ...     ...           ...      ...
2017-11-06  182.010000  182.290000  180.54  180.80  2.022365e+06      0.0
2017-11-07  181.230000  181.780000  180.11  180.89  2.538924e+06      0.0
2017-11-08  181.190000  184.440000  181.06  184.06  1.791296e+06      0.0
2017-11-09  182.880000  183.079000  179.03  181.92  2.703685e+06      0.0
2017-11-10  181.000000  182.060000  179.83  181.72  2.082624e+06      0.0

[11412 rows x 6 columns]
t                  Open       High        Low    Close        Volume  OpenInt
Date
1984-07-19   1.053500   1.055800   1.046900   1.0469  5.302182e+07      0.0
1984-07-20   1.057300   1.064000   1.050600   1.0551  8.783394e+07      0.0
1984-07-21   1.055067   1.062533   1.047667   1.0551  1.208337e+08      0.0
1984-07-22   1.052833   1.061067   1.044733   1.0551  1.538335e+08      0.0
1984-07-23   1.050600   1.059600   1.041800   1.0551  1.868332e+08      0.0
...               ...        ...        ...      ...           ...      ...
2017-11-06  33.070000  33.080000  32.550000  32.8600  4.771826e+07      0.0
2017-11-07  32.830000  33.120000  32.714300  33.0700  3.005612e+07      0.0
2017-11-08  32.850000  33.500000  32.780000  33.4400  8.759120e+07      0.0
2017-11-09  33.430000  34.453000  33.350000  34.0000  6.990463e+07      0.0
2017-11-10  34.170000  34.480000  34.100000  34.2200  5.746612e+07      0.0

[12168 rows x 6 columns]
tmus                  Open       High        Low      Close        Volume  OpenInt
Date
2007-04-18  30.867000  30.867000  30.867000  30.867000  0.000000e+00      0.0
2007-04-19  33.686000  37.054000  32.881000  36.773000  2.367911e+07      0.0
2007-04-20  36.773000  38.651000  36.370000  38.316000  4.552327e+06      0.0
2007-04-21  37.309667  38.713667  36.902333  38.405333  3.966984e+06      0.0
2007-04-22  37.846333  38.776333  37.434667  38.494667  3.381640e+06      0.0
...               ...        ...        ...        ...           ...      ...
2017-11-06  56.200000  56.500000  54.930000  55.540000  1.698181e+07      0.0
2017-11-07  55.780000  56.030000  54.600000  55.350000  8.785391e+06      0.0
2017-11-08  55.360000  56.415000  55.240000  56.220000  5.977832e+06      0.0
2017-11-09  56.500000  56.569000  55.630000  56.000000  5.204316e+06      0.0
2017-11-10  55.690000  57.040000  55.540000  56.800000  5.758882e+06      0.0

[3860 rows x 6 columns]

In [27]:
def drop_old_values(df, yrs):
    cutoff = pd.Timestamp.today() - pd.DateOffset(years = yrs)
    res = df[df.index.get_level_values('Date') >= cutoff]

    return res

dff_recent = drop_old_values(dff, 10)
print(dff_recent)

                     Open       High        Low      Close      Volume  \
Ticker Date
aal    2015-06-02  42.264  43.046000  42.012000  42.733000  15193600.0
       2015-06-03  42.314  42.860000  41.982000  42.100000  13597513.0
       2015-06-04  42.022  42.930000  40.879000  41.161000  14473964.0
       2015-06-05  41.123  41.563000  40.713000  40.723000  10194780.0
       2015-06-06  40.778  41.126333  39.919333  40.117667  15592669.0
...                   ...        ...        ...        ...         ...
tmus   2017-11-06  56.200  56.500000  54.930000  55.540000  16981806.0
       2017-11-07  55.780  56.030000  54.600000  55.350000   8785391.0
       2017-11-08  55.360  56.415000  55.240000  56.220000   5977832.0
       2017-11-09  56.500  56.569000  55.630000  56.000000   5204316.0
       2017-11-10  55.690  57.040000  55.540000  56.800000   5758882.0

                   OpenInt
Ticker Date
aal    2015-06-02      0.0
       2015-06-03      0.0
       2015-06-04      0.0
       2015-06-05      0.0
       2015-06-06      0.0
...                    ...
tmus   2017-11-06      0.0
       2017-11-07      0.0
       2017-11-08      0.0
       2017-11-09      0.0
       2017-11-10      0.0

[4465 rows x 6 columns]

In [28]:
def daily_returns(df, column):
    for stock in stock_names:
        returns_col = [0]
        req_col = df.loc[stock][column].values
        for date in range(len(req_col)-1):
            returns_col.append(req_col[date+1]/req_col[date] - 1)
        
        df.loc[(stock, slice(None)), f'{column}_daily_returns'] = returns_col
    return df

print(daily_returns(dff_recent, 'Close'))

                     Open       High        Low      Close      Volume  \
Ticker Date
aal    2015-06-02  42.264  43.046000  42.012000  42.733000  15193600.0
       2015-06-03  42.314  42.860000  41.982000  42.100000  13597513.0
       2015-06-04  42.022  42.930000  40.879000  41.161000  14473964.0
       2015-06-05  41.123  41.563000  40.713000  40.723000  10194780.0
       2015-06-06  40.778  41.126333  39.919333  40.117667  15592669.0
...                   ...        ...        ...        ...         ...
tmus   2017-11-06  56.200  56.500000  54.930000  55.540000  16981806.0
       2017-11-07  55.780  56.030000  54.600000  55.350000   8785391.0
       2017-11-08  55.360  56.415000  55.240000  56.220000   5977832.0
       2017-11-09  56.500  56.569000  55.630000  56.000000   5204316.0
       2017-11-10  55.690  57.040000  55.540000  56.800000   5758882.0

                   OpenInt  Close_daily_returns
Ticker Date
aal    2015-06-02      0.0             0.000000
       2015-06-03      0.0            -0.014813
       2015-06-04      0.0            -0.022304
       2015-06-05      0.0            -0.010641
       2015-06-06      0.0            -0.014865
...                    ...                  ...
tmus   2017-11-06      0.0            -0.019825
       2017-11-07      0.0            -0.003421
       2017-11-08      0.0             0.015718
       2017-11-09      0.0            -0.003913
       2017-11-10      0.0             0.014286

[4465 rows x 7 columns]

C:\Users\Admin\AppData\Local\Temp\ipykernel_22172\1133870374.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(stock, slice(None)), f'{column}_daily_returns'] = returns_col

In [29]:
def moving_avg(df, days, column):
    for stock in stock_names:
        avg_col = []
        req_col = df.loc[stock][column].values
        for date in range(len(req_col)):
            window = req_col[max(0, date - days + 1) : date + 1]
            moving_avg = np.mean(window)    # use np.nanmean if df isn't clean.
            avg_col.append(moving_avg)
        
        df.loc[(stock, slice(None)), f'{column}_{days}_day_avg'] = avg_col
    return df

print(moving_avg(dff_recent, 7, 'Close'))   
print(moving_avg(dff_recent, 30, 'Close'))

                     Open       High        Low      Close      Volume  \
Ticker Date
aal    2015-06-02  42.264  43.046000  42.012000  42.733000  15193600.0
       2015-06-03  42.314  42.860000  41.982000  42.100000  13597513.0
       2015-06-04  42.022  42.930000  40.879000  41.161000  14473964.0
       2015-06-05  41.123  41.563000  40.713000  40.723000  10194780.0
       2015-06-06  40.778  41.126333  39.919333  40.117667  15592669.0
...                   ...        ...        ...        ...         ...
tmus   2017-11-06  56.200  56.500000  54.930000  55.540000  16981806.0
       2017-11-07  55.780  56.030000  54.600000  55.350000   8785391.0
       2017-11-08  55.360  56.415000  55.240000  56.220000   5977832.0
       2017-11-09  56.500  56.569000  55.630000  56.000000   5204316.0
       2017-11-10  55.690  57.040000  55.540000  56.800000   5758882.0

                   OpenInt  Close_daily_returns  Close_7_day_avg
Ticker Date
aal    2015-06-02      0.0             0.000000        42.733000
       2015-06-03      0.0            -0.014813        42.416500
       2015-06-04      0.0            -0.022304        41.998000
       2015-06-05      0.0            -0.010641        41.679250
       2015-06-06      0.0            -0.014865        41.366933
...                    ...                  ...              ...
tmus   2017-11-06      0.0            -0.019825        58.102857
       2017-11-07      0.0            -0.003421        57.471429
       2017-11-08      0.0             0.015718        56.967143
       2017-11-09      0.0            -0.003913        56.638571
       2017-11-10      0.0             0.014286        56.337143

[4465 rows x 8 columns]
                     Open       High        Low      Close      Volume  \
Ticker Date
aal    2015-06-02  42.264  43.046000  42.012000  42.733000  15193600.0
       2015-06-03  42.314  42.860000  41.982000  42.100000  13597513.0
       2015-06-04  42.022  42.930000  40.879000  41.161000  14473964.0
       2015-06-05  41.123  41.563000  40.713000  40.723000  10194780.0
       2015-06-06  40.778  41.126333  39.919333  40.117667  15592669.0
...                   ...        ...        ...        ...         ...
tmus   2017-11-06  56.200  56.500000  54.930000  55.540000  16981806.0
       2017-11-07  55.780  56.030000  54.600000  55.350000   8785391.0
       2017-11-08  55.360  56.415000  55.240000  56.220000   5977832.0
       2017-11-09  56.500  56.569000  55.630000  56.000000   5204316.0
       2017-11-10  55.690  57.040000  55.540000  56.800000   5758882.0

                   OpenInt  Close_daily_returns  Close_7_day_avg  \
Ticker Date
aal    2015-06-02      0.0             0.000000        42.733000
       2015-06-03      0.0            -0.014813        42.416500
       2015-06-04      0.0            -0.022304        41.998000
       2015-06-05      0.0            -0.010641        41.679250
       2015-06-06      0.0            -0.014865        41.366933
...                    ...                  ...              ...
tmus   2017-11-06      0.0            -0.019825        58.102857
       2017-11-07      0.0            -0.003421        57.471429
       2017-11-08      0.0             0.015718        56.967143
       2017-11-09      0.0            -0.003913        56.638571
       2017-11-10      0.0             0.014286        56.337143

                   Close_30_day_avg
Ticker Date
aal    2015-06-02         42.733000
       2015-06-03         42.416500
       2015-06-04         41.998000
       2015-06-05         41.679250
       2015-06-06         41.366933
...                             ...
tmus   2017-11-06         60.550778
       2017-11-07         60.334333
       2017-11-08         60.156333
       2017-11-09         59.982000
       2017-11-10         59.836000

[4465 rows x 9 columns]

C:\Users\Admin\AppData\Local\Temp\ipykernel_22172\1324256139.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(stock, slice(None)), f'{column}_{days}_day_avg'] = avg_col
C:\Users\Admin\AppData\Local\Temp\ipykernel_22172\1324256139.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(stock, slice(None)), f'{column}_{days}_day_avg'] = avg_col

In [30]:
def rolling_volatility(df, days, column):
    for stock in stock_names:
        std_dev_col = []
        req_col = df.loc[stock][column].values
        for date in range(len(req_col)):
            window = req_col[max(0, date - days + 1) : date + 1]
            std_dev = np.std(window)
            std_dev_col.append(std_dev)

        df.loc[(stock, slice(None)), f'{column}_{days}_day_volatility'] = std_dev_col

    return df

print(rolling_volatility(dff_recent, 30, 'Close'))

                     Open       High        Low      Close      Volume  \
Ticker Date
aal    2015-06-02  42.264  43.046000  42.012000  42.733000  15193600.0
       2015-06-03  42.314  42.860000  41.982000  42.100000  13597513.0
       2015-06-04  42.022  42.930000  40.879000  41.161000  14473964.0
       2015-06-05  41.123  41.563000  40.713000  40.723000  10194780.0
       2015-06-06  40.778  41.126333  39.919333  40.117667  15592669.0
...                   ...        ...        ...        ...         ...
tmus   2017-11-06  56.200  56.500000  54.930000  55.540000  16981806.0
       2017-11-07  55.780  56.030000  54.600000  55.350000   8785391.0
       2017-11-08  55.360  56.415000  55.240000  56.220000   5977832.0
       2017-11-09  56.500  56.569000  55.630000  56.000000   5204316.0
       2017-11-10  55.690  57.040000  55.540000  56.800000   5758882.0

                   OpenInt  Close_daily_returns  Close_7_day_avg  \
Ticker Date
aal    2015-06-02      0.0             0.000000        42.733000
       2015-06-03      0.0            -0.014813        42.416500
       2015-06-04      0.0            -0.022304        41.998000
       2015-06-05      0.0            -0.010641        41.679250
       2015-06-06      0.0            -0.014865        41.366933
...                    ...                  ...              ...
tmus   2017-11-06      0.0            -0.019825        58.102857
       2017-11-07      0.0            -0.003421        57.471429
       2017-11-08      0.0             0.015718        56.967143
       2017-11-09      0.0            -0.003913        56.638571
       2017-11-10      0.0             0.014286        56.337143

                   Close_30_day_avg  Close_30_day_volatility
Ticker Date
aal    2015-06-02         42.733000                 0.000000
       2015-06-03         42.416500                 0.316500
       2015-06-04         41.998000                 0.645806
       2015-06-05         41.679250                 0.785878
       2015-06-06         41.366933                 0.940346
...                             ...                      ...
tmus   2017-11-06         60.550778                 1.628942
       2017-11-07         60.334333                 1.858095
       2017-11-08         60.156333                 1.983688
       2017-11-09         59.982000                 2.107614
       2017-11-10         59.836000                 2.170342

[4465 rows x 10 columns]

C:\Users\Admin\AppData\Local\Temp\ipykernel_22172\2005244452.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(stock, slice(None)), f'{column}_{days}_day_volatility'] = std_dev_col